name: Relases
on:
 push:
  branches:
   - main
 pull_request:
   branches:
    - main
jobs:
   changelog:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          skip-version-file: 'true'
      
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{steps.changelong.outputs.skipped == 'false'}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.changelog.outputs.tag}}
          release_name: ${{steps.changelog.outputs.tag}}
          body: ${{steps.changelog.outputs.body}}
